### ISSUE TITLE
../github.com/oasisprotocol/curve25519-voi/internal/toolchain/constraints.go:48:6: undefined: __SOFTWARE_REQUIRES_GO_VERSION_1_18__

### ISSUE THREAD

**Issue by gouserdev** [oasisprotocol/curve25519-voi#119]
../github.com/oasisprotocol/curve25519-voi/internal/toolchain/constraints.go:48:6: undefined: __SOFTWARE_REQUIRES_GO_VERSION_1_18__

**Comment by Yawning** [comment]
Gee I wonder what that error means, given the descriptively named constant.

WONTFIX
